/* GENERATED by measure.py. Do not hand-edit: re-run the script.
   Measured offline with Playwright, which can read inside cross-origin
   frames. A published page cannot, which is why this data is baked. */
const MEASUREMENTS = {
 "measuredAt": "2026-09-04",
 "frameWidth": 640,
 "narrowWidth": 375,
 "players": {
  "iheart": {
   "id": "iheart",
   "name": "iHeartRadio",
   "group": "parity",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 200,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 60,
      "h": 60,
      "area": 3600,
      "via": "aria-label",
      "cx": 0.1,
      "cy": 0.8,
      "radius": "0px",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": {
      "kind": "bars",
      "count": 166,
      "w": 498,
      "h": 30
     },
     "artwork": {
      "w": 70,
      "h": 70,
      "areaShare": 0,
      "cx": 0.9,
      "cy": 0.8,
      "radius": "6px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:00"
     ],
     "controlCount": 7,
     "outboundLinks": 4,
     "platformPush": false,
     "textLen": 119,
     "textSample": "iHeart Social Identity Theory: Your Group Rules, Others Drool - Stuff You Should Know Stuff You Should Know 00:00 00:00",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 60,
      "h": 60,
      "area": 3600,
      "via": "aria-label",
      "cx": 0.1,
      "cy": 0.8,
      "radius": "0px",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": {
      "kind": "bars",
      "count": 166,
      "w": 498,
      "h": 30
     },
     "artwork": {
      "w": 70,
      "h": 70,
      "areaShare": 0,
      "cx": 0.9,
      "cy": 0.8,
      "radius": "6px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:00"
     ],
     "controlCount": 7,
     "outboundLinks": 4,
     "platformPush": false,
     "textLen": 119,
     "textSample": "iHeart Social Identity Theory: Your Group Rules, Others Drool - Stuff You Should Know Stuff You Should Know 00:00 00:00",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 23,
    "kb": 12.6
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 200,
    "clientH": 200
   },
   "pixels": {
    "light": 233.3,
    "dark": 233.3
   },
   "themeResponds": false,
   "lightLuma": 233.3,
   "darkLuma": 233.3,
   "measured": true
  },
  "tunein": {
   "id": "tunein",
   "name": "TuneIn",
   "group": "parity",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 350,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 398
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 40,
      "h": 40,
      "area": 1600,
      "via": "class",
      "cx": 0.2,
      "cy": 0.1,
      "radius": "50%",
      "accessibleName": null,
      "tag": "div"
     },
     "waveform": null,
     "artwork": {
      "w": 80,
      "h": 80,
      "areaShare": 0,
      "cx": 0.1,
      "cy": 0.1,
      "radius": "3px",
      "isImg": true
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 483,
      "h": 4,
      "interactive": false
     },
     "timecodes": [
      "00:47:32",
      "00:12:12",
      "00:46:47",
      "00:50:18"
     ],
     "controlCount": 10,
     "outboundLinks": 5,
     "platformPush": true,
     "textLen": 1622,
     "textSample": "Hear what you want, where and when you want it, download the TuneIn app today. LISTEN FREE IN APP Share with Facebook Tw",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 398
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 40,
      "h": 40,
      "area": 1600,
      "via": "class",
      "cx": 0.2,
      "cy": 0.1,
      "radius": "50%",
      "accessibleName": null,
      "tag": "div"
     },
     "waveform": null,
     "artwork": {
      "w": 80,
      "h": 80,
      "areaShare": 0,
      "cx": 0.1,
      "cy": 0.1,
      "radius": "3px",
      "isImg": true
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 483,
      "h": 4,
      "interactive": false
     },
     "timecodes": [
      "00:47:32",
      "00:12:12",
      "00:46:47",
      "00:50:18"
     ],
     "controlCount": 10,
     "outboundLinks": 5,
     "platformPush": true,
     "textLen": 1622,
     "textSample": "Hear what you want, where and when you want it, download the TuneIn app today. LISTEN FREE IN APP Share with Facebook Tw",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 45,
    "kb": 4.0
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 398,
    "clientH": 350
   },
   "pixels": {
    "light": 236.0,
    "dark": 236.0
   },
   "themeResponds": false,
   "lightLuma": 236.0,
   "darkLuma": 236.0,
   "measured": true
  },
  "youtube": {
   "id": "youtube",
   "name": "YouTube",
   "group": "parity",
   "status": "ok",
   "blocked": false,
   "declaredHeight": null,
   "aspect": true,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgb(0, 0, 0)",
     "color": "rgb(255, 255, 255)",
     "radius": "0px",
     "play": {
      "w": 72,
      "h": 72,
      "area": 5184,
      "via": "class",
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "accessibleName": null,
      "tag": "c3-icon"
     },
     "waveform": null,
     "artwork": {
      "w": 640,
      "h": 360,
      "areaShare": 1,
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "isImg": false
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 7,
     "outboundLinks": 2,
     "platformPush": true,
     "textLen": 110,
     "textSample": "Save the Whales! | STUFF YOU SHOULD KNOW Stuff You Should Know Stuff You Should Know 228K subscribers Watch on",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgb(0, 0, 0)",
     "color": "rgb(255, 255, 255)",
     "radius": "0px",
     "play": {
      "w": 72,
      "h": 72,
      "area": 5184,
      "via": "class",
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "accessibleName": null,
      "tag": "c3-icon"
     },
     "waveform": null,
     "artwork": {
      "w": 640,
      "h": 360,
      "areaShare": 1,
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "isImg": false
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 7,
     "outboundLinks": 2,
     "platformPush": true,
     "textLen": 110,
     "textSample": "Save the Whales! | STUFF YOU SHOULD KNOW Stuff You Should Know Stuff You Should Know 228K subscribers Watch on",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 18,
    "kb": 0.1
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 360,
    "clientH": 360
   },
   "pixels": {
    "light": 81.3,
    "dark": 81.3
   },
   "themeResponds": false,
   "lightLuma": 81.3,
   "darkLuma": 81.3,
   "measured": true
  },
  "applepodcasts": {
   "id": "applepodcasts",
   "name": "Apple Podcasts",
   "group": "parity",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 165,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 165
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgba(0, 0, 0, 0.88)",
     "radius": "0px",
     "play": {
      "w": 67.7,
      "h": 28,
      "area": 1897,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.8,
      "radius": "40px",
      "accessibleName": "Play, 48m",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 132,
      "h": 132,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "6px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 5,
     "outboundLinks": 3,
     "platformPush": false,
     "textLen": 117,
     "textSample": "1d ago Social Identity Theory: Your Group Rules, Others Drool Stuff You Should Know 48m See how your data is managed\u2026",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 165
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgba(255, 255, 255, 0.92)",
     "radius": "0px",
     "play": {
      "w": 67.7,
      "h": 28,
      "area": 1897,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.8,
      "radius": "40px",
      "accessibleName": "Play, 48m",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 132,
      "h": 132,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "6px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 5,
     "outboundLinks": 3,
     "platformPush": false,
     "textLen": 117,
     "textSample": "1d ago Social Identity Theory: Your Group Rules, Others Drool Stuff You Should Know 48m See how your data is managed\u2026",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 13,
    "kb": 1.3
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 165,
    "clientH": 165
   },
   "pixels": {
    "light": 72.4,
    "dark": 72.4
   },
   "themeResponds": false,
   "lightLuma": 72.4,
   "darkLuma": 72.4,
   "measured": true
  },
  "spotify": {
   "id": "spotify",
   "name": "Spotify",
   "group": "parity",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 152,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 152
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(255, 255, 255)",
     "radius": "0px",
     "play": {
      "w": 32,
      "h": 32,
      "area": 1024,
      "via": "aria-label",
      "cx": 1,
      "cy": 0.8,
      "radius": "50%",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 120,
      "h": 120,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "8px",
      "isImg": true
     },
     "progress": {
      "kind": "input",
      "w": 129,
      "h": 16,
      "interactive": true
     },
     "timecodes": [
      "47:31"
     ],
     "controlCount": 10,
     "outboundLinks": 3,
     "platformPush": true,
     "textLen": 122,
     "textSample": "Social Identity Theory: Your Group Rules, Others Drool Sep 3 \u00b7 Stuff You Should Know Save on Spotify Change progress 47:",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 152
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(255, 255, 255)",
     "radius": "0px",
     "play": {
      "w": 32,
      "h": 32,
      "area": 1024,
      "via": "aria-label",
      "cx": 1,
      "cy": 0.8,
      "radius": "50%",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 120,
      "h": 120,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "8px",
      "isImg": true
     },
     "progress": {
      "kind": "input",
      "w": 129,
      "h": 16,
      "interactive": true
     },
     "timecodes": [
      "47:31"
     ],
     "controlCount": 10,
     "outboundLinks": 3,
     "platformPush": true,
     "textLen": 122,
     "textSample": "Social Identity Theory: Your Group Rules, Others Drool Sep 3 \u00b7 Stuff You Should Know Save on Spotify Change progress 47:",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 34,
    "kb": 416.4
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 152,
    "clientH": 152
   },
   "pixels": {
    "light": 48.3,
    "dark": 48.3
   },
   "themeResponds": false,
   "lightLuma": 48.3,
   "darkLuma": 48.3,
   "measured": true
  },
  "deezer": {
   "id": "deezer",
   "name": "Deezer",
   "group": "parity",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 300,
   "aspect": false,
   "themedParam": true,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 300
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 48,
      "h": 48,
      "area": 2304,
      "via": "class",
      "cx": 0.5,
      "cy": 0.9,
      "radius": "100%",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 640,
      "h": 300,
      "areaShare": 1,
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 4,
     "outboundLinks": 3,
     "platformPush": false,
     "textLen": 126,
     "textSample": "Stuff You Should Know Social Identity Theory: Your Group Rules, Others Drool Play Track Handle /widget/light/episode/929",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 300
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 48,
      "h": 48,
      "area": 2304,
      "via": "class",
      "cx": 0.5,
      "cy": 0.9,
      "radius": "100%",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 640,
      "h": 300,
      "areaShare": 1,
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 4,
     "outboundLinks": 3,
     "platformPush": false,
     "textLen": 126,
     "textSample": "Stuff You Should Know Social Identity Theory: Your Group Rules, Others Drool Play Track Handle /widget/light/episode/929",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 37,
    "kb": 55028.4
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 300,
    "clientH": 300
   },
   "pixels": {
    "light": 48.1,
    "dark": 48.1
   },
   "themeResponds": false,
   "lightLuma": 48.1,
   "darkLuma": 48.1,
   "measured": true
  },
  "omny": {
   "id": "omny",
   "name": "Omny Studio",
   "group": "parity",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 200,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 60,
      "h": 60,
      "area": 3600,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.4,
      "radius": "50%",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 396,
      "h": 28
     },
     "artwork": {
      "w": 156,
      "h": 156,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "input",
      "w": 1,
      "h": 1,
      "interactive": true
     },
     "timecodes": [
      "00:00",
      "47:31"
     ],
     "controlCount": 6,
     "outboundLinks": 1,
     "platformPush": false,
     "textLen": 145,
     "textSample": "Stuff You Should Know Social Identity Theory: Your Group Rules, Others Drool Social Identity Theory: Your Group Rules, O",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 60,
      "h": 60,
      "area": 3600,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.4,
      "radius": "50%",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 396,
      "h": 28
     },
     "artwork": {
      "w": 156,
      "h": 156,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "input",
      "w": 1,
      "h": 1,
      "interactive": true
     },
     "timecodes": [
      "00:00",
      "47:31"
     ],
     "controlCount": 6,
     "outboundLinks": 1,
     "platformPush": false,
     "textLen": 145,
     "textSample": "Stuff You Should Know Social Identity Theory: Your Group Rules, Others Drool Social Identity Theory: Your Group Rules, O",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 32,
    "kb": null
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 200,
    "clientH": 200
   },
   "pixels": {
    "light": 85.4,
    "dark": 85.4
   },
   "themeResponds": false,
   "lightLuma": 85.4,
   "darkLuma": 85.4,
   "measured": true
  },
  "megaphone": {
   "id": "megaphone",
   "name": "Megaphone",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 374,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 374
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 40,
      "h": 40,
      "area": 1600,
      "via": "class",
      "cx": 0.4,
      "cy": 0.1,
      "radius": "50%",
      "accessibleName": null,
      "tag": "div"
     },
     "waveform": null,
     "artwork": {
      "w": 200,
      "h": 200,
      "areaShare": 0.2,
      "cx": 0.2,
      "cy": 0.3,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:54:06"
     ],
     "controlCount": 0,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 77,
     "textSample": "Reply All Big Lives: Emmanuel's New Show 00:54:06 SHARESUBSCRIBECOOKIE POLICY",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 374
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 40,
      "h": 40,
      "area": 1600,
      "via": "class",
      "cx": 0.4,
      "cy": 0.1,
      "radius": "50%",
      "accessibleName": null,
      "tag": "div"
     },
     "waveform": null,
     "artwork": {
      "w": 200,
      "h": 200,
      "areaShare": 0.2,
      "cx": 0.2,
      "cy": 0.3,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:54:06"
     ],
     "controlCount": 0,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 77,
     "textSample": "Reply All Big Lives: Emmanuel's New Show 00:54:06 SHARESUBSCRIBECOOKIE POLICY",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 13,
    "kb": 507.5
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 374,
    "clientH": 374
   },
   "pixels": {
    "light": 163.3,
    "dark": 163.4
   },
   "themeResponds": false,
   "lightLuma": 163.3,
   "darkLuma": 163.4,
   "measured": true
  },
  "acast": {
   "id": "acast",
   "name": "Acast",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 200,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(207, 229, 252)",
     "radius": "8px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 180,
      "h": 180,
      "areaShare": 0.3,
      "cx": 0.2,
      "cy": 0.5,
      "radius": "4px",
      "isImg": true
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 430,
      "h": 4,
      "interactive": false
     },
     "timecodes": [],
     "controlCount": 4,
     "outboundLinks": 3,
     "platformPush": false,
     "textLen": 132,
     "textSample": "Economist Podcasts Can humans keep control of AI? Full episode available for members. Learn more September 4, 2026 29 mi",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(207, 229, 252)",
     "radius": "8px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 180,
      "h": 180,
      "areaShare": 0.3,
      "cx": 0.2,
      "cy": 0.5,
      "radius": "4px",
      "isImg": true
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 430,
      "h": 4,
      "interactive": false
     },
     "timecodes": [],
     "controlCount": 4,
     "outboundLinks": 3,
     "platformPush": false,
     "textLen": 132,
     "textSample": "Economist Podcasts Can humans keep control of AI? Full episode available for members. Learn more September 4, 2026 29 mi",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 11,
    "kb": 179.7
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 200,
    "clientH": 200
   },
   "pixels": {
    "light": 56.4,
    "dark": 56.4
   },
   "themeResponds": false,
   "lightLuma": 56.4,
   "darkLuma": 56.4,
   "measured": true
  },
  "libsyn": {
   "id": "libsyn",
   "name": "Libsyn",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 100,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 100
     },
     "bg": "rgb(255, 255, 255)",
     "color": "rgb(51, 51, 51)",
     "radius": "0px",
     "play": {
      "w": 80,
      "h": 40.6,
      "area": 3248,
      "via": "aria-label",
      "cx": 0.2,
      "cy": 0.3,
      "radius": "0px",
      "accessibleName": "Play Episode",
      "tag": "a"
     },
     "waveform": null,
     "artwork": {
      "w": 90,
      "h": 90,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:00:00"
     ],
     "controlCount": 7,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 136,
     "textSample": "REAL MONEY REAL BUSINESS PODCAST RMRB 1149 - Building a YouTube Business Making $18K per Month in the Entertainment Nich",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 100
     },
     "bg": "rgb(255, 255, 255)",
     "color": "rgb(51, 51, 51)",
     "radius": "0px",
     "play": {
      "w": 80,
      "h": 40.6,
      "area": 3248,
      "via": "aria-label",
      "cx": 0.2,
      "cy": 0.3,
      "radius": "0px",
      "accessibleName": "Play Episode",
      "tag": "a"
     },
     "waveform": null,
     "artwork": {
      "w": 90,
      "h": 90,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:00:00"
     ],
     "controlCount": 7,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 136,
     "textSample": "REAL MONEY REAL BUSINESS PODCAST RMRB 1149 - Building a YouTube Business Making $18K per Month in the Entertainment Nich",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 24,
    "kb": 1.4
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 100,
    "clientH": 100
   },
   "pixels": {
    "light": 229.6,
    "dark": 229.6
   },
   "themeResponds": false,
   "lightLuma": 229.6,
   "darkLuma": 229.6,
   "measured": true
  },
  "captivate": {
   "id": "captivate",
   "name": "Captivate",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 200,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgb(199, 175, 207)",
     "color": "rgb(33, 37, 41)",
     "radius": "0px",
     "play": {
      "w": 42,
      "h": 42,
      "area": 1764,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.8,
      "radius": "0px",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 168,
      "h": 168,
      "areaShare": 0.2,
      "cx": 0.2,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "slider",
      "w": 24,
      "h": 20,
      "interactive": true
     },
     "timecodes": [
      "00:00:00",
      "00:22:19"
     ],
     "controlCount": 11,
     "outboundLinks": 1,
     "platformPush": false,
     "textLen": 168,
     "textSample": "The Push to Recall Sheriff Gerald Couch | More to the Story Ep. 1 Episode 1 \u2022 27th August 2026 \u2022 More to the Story \u2022 Sta",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgb(199, 175, 207)",
     "color": "rgb(33, 37, 41)",
     "radius": "0px",
     "play": {
      "w": 42,
      "h": 42,
      "area": 1764,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.8,
      "radius": "0px",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 168,
      "h": 168,
      "areaShare": 0.2,
      "cx": 0.2,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "slider",
      "w": 24,
      "h": 20,
      "interactive": true
     },
     "timecodes": [
      "00:00:00",
      "00:22:19"
     ],
     "controlCount": 11,
     "outboundLinks": 1,
     "platformPush": false,
     "textLen": 168,
     "textSample": "The Push to Recall Sheriff Gerald Couch | More to the Story Ep. 1 Episode 1 \u2022 27th August 2026 \u2022 More to the Story \u2022 Sta",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 20,
    "kb": null
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 200,
    "clientH": 200
   },
   "pixels": {
    "light": 161.7,
    "dark": 161.7
   },
   "themeResponds": false,
   "lightLuma": 161.7,
   "darkLuma": 161.7,
   "measured": true
  },
  "transistor": {
   "id": "transistor",
   "name": "Transistor",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 200,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 52.8,
      "h": 52.8,
      "area": 2788,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.5,
      "radius": "0px",
      "accessibleName": "Play",
      "tag": "span"
     },
     "waveform": null,
     "artwork": {
      "w": 154,
      "h": 154,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "6px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:00",
      "47:54"
     ],
     "controlCount": 11,
     "outboundLinks": 1,
     "platformPush": false,
     "textLen": 113,
     "textSample": "HIGH SPEED RAIL TALK EPISODE 1 A New Transit Hub for Detroit 00:00 10 1X 30 00:00 47:54 SUBSCRIBE SHARE MORE INFO",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 52.8,
      "h": 52.8,
      "area": 2788,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.5,
      "radius": "0px",
      "accessibleName": "Play",
      "tag": "span"
     },
     "waveform": null,
     "artwork": {
      "w": 154,
      "h": 154,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "6px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:00",
      "47:54"
     ],
     "controlCount": 11,
     "outboundLinks": 1,
     "platformPush": false,
     "textLen": 113,
     "textSample": "HIGH SPEED RAIL TALK EPISODE 1 A New Transit Hub for Detroit 00:00 10 1X 30 00:00 47:54 SUBSCRIBE SHARE MORE INFO",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 4,
    "kb": 21.3
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 200,
    "clientH": 200
   },
   "pixels": {
    "light": 228.0,
    "dark": 228.0
   },
   "themeResponds": false,
   "lightLuma": 228.0,
   "darkLuma": 228.0,
   "measured": true
  },
  "simplecast": {
   "id": "simplecast",
   "name": "Simplecast",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 200,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(15, 15, 15)",
     "radius": "0px",
     "play": {
      "w": 70,
      "h": 70,
      "area": 4900,
      "via": "aria-label",
      "cx": 0.4,
      "cy": 0.7,
      "radius": "100%",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 164,
      "h": 164,
      "areaShare": 0.2,
      "cx": 0.2,
      "cy": 0.5,
      "radius": "2px",
      "isImg": false
     },
     "progress": null,
     "timecodes": [
      "00:00",
      "18:39"
     ],
     "controlCount": 8,
     "outboundLinks": 2,
     "platformPush": false,
     "textLen": 209,
     "textSample": "Busted Open | EP2449 Busted Open | EP2449 Busted Open | EP2449 BOAD: Roman Reigns Returns on RAW BOAD: Roman Reigns Retu",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(15, 15, 15)",
     "radius": "0px",
     "play": {
      "w": 70,
      "h": 70,
      "area": 4900,
      "via": "aria-label",
      "cx": 0.4,
      "cy": 0.7,
      "radius": "100%",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 164,
      "h": 164,
      "areaShare": 0.2,
      "cx": 0.2,
      "cy": 0.5,
      "radius": "2px",
      "isImg": false
     },
     "progress": null,
     "timecodes": [
      "00:00",
      "18:39"
     ],
     "controlCount": 8,
     "outboundLinks": 2,
     "platformPush": false,
     "textLen": 209,
     "textSample": "Busted Open | EP2449 Busted Open | EP2449 Busted Open | EP2449 BOAD: Roman Reigns Returns on RAW BOAD: Roman Reigns Retu",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 8,
    "kb": 1.1
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 200,
    "clientH": 200
   },
   "pixels": {
    "light": 59.6,
    "dark": 59.6
   },
   "themeResponds": false,
   "lightLuma": 59.6,
   "darkLuma": 59.6,
   "measured": true
  },
  "audioboom": {
   "id": "audioboom",
   "name": "Audioboom",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 300,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 300
     },
     "bg": "rgb(237, 239, 239)",
     "color": "rgb(33, 37, 41)",
     "radius": "0px",
     "play": {
      "w": 74,
      "h": 74,
      "area": 5476,
      "via": "aria-label",
      "cx": 0.1,
      "cy": 0.7,
      "radius": "6px",
      "accessibleName": "play audio",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 56,
      "h": 56,
      "areaShare": 0,
      "cx": 0.9,
      "cy": 0.7,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 5,
     "outboundLinks": 2,
     "platformPush": false,
     "textLen": 64,
     "textSample": "Mayhem In Minneapolis Mayhem In Minneapolis What A Day SUBSCRIBE",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 300
     },
     "bg": "rgb(237, 239, 239)",
     "color": "rgb(33, 37, 41)",
     "radius": "0px",
     "play": {
      "w": 74,
      "h": 74,
      "area": 5476,
      "via": "aria-label",
      "cx": 0.1,
      "cy": 0.7,
      "radius": "6px",
      "accessibleName": "play audio",
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 56,
      "h": 56,
      "areaShare": 0,
      "cx": 0.9,
      "cy": 0.7,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 5,
     "outboundLinks": 2,
     "platformPush": false,
     "textLen": 64,
     "textSample": "Mayhem In Minneapolis Mayhem In Minneapolis What A Day SUBSCRIBE",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 47,
    "kb": null
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 300,
    "clientH": 300
   },
   "pixels": {
    "light": 111.7,
    "dark": 111.7
   },
   "themeResponds": false,
   "lightLuma": 111.7,
   "darkLuma": 111.7,
   "measured": true
  },
  "spreaker": {
   "id": "spreaker",
   "name": "Spreaker",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 200,
   "aspect": false,
   "themedParam": true,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(76, 76, 76)",
     "radius": "0px",
     "play": {
      "w": 72,
      "h": 72,
      "area": 5184,
      "via": "aria-label",
      "cx": 0.1,
      "cy": 0.2,
      "radius": "50%",
      "accessibleName": "Play episode Sara Escudero - Detalles que ilusionan",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 438,
      "h": 72
     },
     "artwork": {
      "w": 200,
      "h": 200,
      "areaShare": 0.3,
      "cx": 0.8,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:00",
      "18:41"
     ],
     "controlCount": 10,
     "outboundLinks": 5,
     "platformPush": false,
     "textLen": 65,
     "textSample": "Sara Escudero - Detalles que ilusionan Privacy Policy 00:00 18:41",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(76, 76, 76)",
     "radius": "0px",
     "play": {
      "w": 72,
      "h": 72,
      "area": 5184,
      "via": "aria-label",
      "cx": 0.1,
      "cy": 0.2,
      "radius": "50%",
      "accessibleName": "Play episode Sara Escudero - Detalles que ilusionan",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 438,
      "h": 72
     },
     "artwork": {
      "w": 200,
      "h": 200,
      "areaShare": 0.3,
      "cx": 0.8,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:00",
      "18:41"
     ],
     "controlCount": 10,
     "outboundLinks": 5,
     "platformPush": false,
     "textLen": 65,
     "textSample": "Sara Escudero - Detalles que ilusionan Privacy Policy 00:00 18:41",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 6,
    "kb": 68.4
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 200,
    "clientH": 200
   },
   "pixels": {
    "light": 218.5,
    "dark": 218.5
   },
   "themeResponds": false,
   "lightLuma": 218.5,
   "darkLuma": 218.5,
   "measured": true
  },
  "podbean": {
   "id": "podbean",
   "name": "Podbean",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 150,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 150
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(33, 37, 41)",
     "radius": "0px",
     "play": {
      "w": 44,
      "h": 44,
      "area": 1936,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.5,
      "radius": "25px",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 490,
      "h": 34
     },
     "artwork": {
      "w": 148,
      "h": 148,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "4px",
      "isImg": true
     },
     "progress": {
      "kind": "slider",
      "w": 416,
      "h": 3.7,
      "interactive": true
     },
     "timecodes": [
      "0:00"
     ],
     "controlCount": 9,
     "outboundLinks": 5,
     "platformPush": false,
     "textLen": 166,
     "textSample": "Sleep & Relaxation Music to Calm the Nervous System Celestial Sleep ~ Calming Music For Deep Sleep & Meditation Play Cur",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 150
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(33, 37, 41)",
     "radius": "0px",
     "play": {
      "w": 44,
      "h": 44,
      "area": 1936,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.5,
      "radius": "25px",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 490,
      "h": 34
     },
     "artwork": {
      "w": 148,
      "h": 148,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "4px",
      "isImg": true
     },
     "progress": {
      "kind": "slider",
      "w": 416,
      "h": 3.7,
      "interactive": true
     },
     "timecodes": [
      "0:00"
     ],
     "controlCount": 9,
     "outboundLinks": 5,
     "platformPush": false,
     "textLen": 166,
     "textSample": "Sleep & Relaxation Music to Calm the Nervous System Celestial Sleep ~ Calming Music For Deep Sleep & Meditation Play Cur",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 16,
    "kb": null
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 150,
    "clientH": 150
   },
   "pixels": {
    "light": 192.6,
    "dark": 192.6
   },
   "themeResponds": false,
   "lightLuma": 192.6,
   "darkLuma": 192.6,
   "measured": true
  },
  "buzzsprout": {
   "id": "buzzsprout",
   "name": "Buzzsprout",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 200,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 35,
      "h": 35,
      "area": 1225,
      "via": "aria-label",
      "cx": 0.4,
      "cy": 0.6,
      "radius": "0px",
      "accessibleName": "Play Icon",
      "tag": "svg"
     },
     "waveform": null,
     "artwork": {
      "w": 170,
      "h": 170,
      "areaShare": 0.2,
      "cx": 0.2,
      "cy": 0.5,
      "radius": "10px",
      "isImg": false
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 351,
      "h": 5,
      "interactive": false
     },
     "timecodes": [
      "00:00",
      "51:15"
     ],
     "controlCount": 7,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 76,
     "textSample": "#001 - Sam Altman - CEO of Open AI The Joe Rogan AI Experience 00:00 | 51:15",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 35,
      "h": 35,
      "area": 1225,
      "via": "aria-label",
      "cx": 0.4,
      "cy": 0.6,
      "radius": "0px",
      "accessibleName": "Play Icon",
      "tag": "svg"
     },
     "waveform": null,
     "artwork": {
      "w": 170,
      "h": 170,
      "areaShare": 0.2,
      "cx": 0.2,
      "cy": 0.5,
      "radius": "10px",
      "isImg": false
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 351,
      "h": 5,
      "interactive": false
     },
     "timecodes": [
      "00:00",
      "51:15"
     ],
     "controlCount": 7,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 76,
     "textSample": "#001 - Sam Altman - CEO of Open AI The Joe Rogan AI Experience 00:00 | 51:15",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 11,
    "kb": 53.5
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 200,
    "clientH": 200
   },
   "pixels": {
    "light": 192.5,
    "dark": 192.5
   },
   "themeResponds": false,
   "lightLuma": 192.5,
   "darkLuma": 192.5,
   "measured": true
  },
  "blubrry": {
   "id": "blubrry",
   "name": "Blubrry",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 172,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 172
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(51, 51, 51)",
     "radius": "0px",
     "play": {
      "w": 26.1,
      "h": 26.1,
      "area": 683,
      "via": "aria-label",
      "cx": 0.9,
      "cy": 0.8,
      "radius": "16px",
      "accessibleName": "Play Speed 1x",
      "tag": "a"
     },
     "waveform": null,
     "artwork": {
      "w": 160,
      "h": 160,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "5px",
      "isImg": true
     },
     "progress": {
      "kind": "input",
      "w": 129,
      "h": 1.5,
      "interactive": true
     },
     "timecodes": [
      "00:00"
     ],
     "controlCount": 7,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 91,
     "textSample": "The World and Everything In It DoubleTake: The kidnapping of Kayla Mueller, Part II 00:00 |",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 172
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(51, 51, 51)",
     "radius": "0px",
     "play": {
      "w": 26.1,
      "h": 26.1,
      "area": 683,
      "via": "aria-label",
      "cx": 0.9,
      "cy": 0.8,
      "radius": "16px",
      "accessibleName": "Play Speed 1x",
      "tag": "a"
     },
     "waveform": null,
     "artwork": {
      "w": 160,
      "h": 160,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "5px",
      "isImg": true
     },
     "progress": {
      "kind": "input",
      "w": 129,
      "h": 1.5,
      "interactive": true
     },
     "timecodes": [
      "00:00"
     ],
     "controlCount": 7,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 91,
     "textSample": "The World and Everything In It DoubleTake: The kidnapping of Kayla Mueller, Part II 00:00 |",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 5,
    "kb": 5.0
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 172,
    "clientH": 172
   },
   "pixels": {
    "light": 206.9,
    "dark": 206.9
   },
   "themeResponds": false,
   "lightLuma": 206.9,
   "darkLuma": 206.9,
   "measured": true
  },
  "castbox": {
   "id": "castbox",
   "name": "Castbox",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 210,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 210
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(33, 37, 41)",
     "radius": "0px",
     "play": {
      "w": 60,
      "h": 60,
      "area": 3600,
      "via": "class",
      "cx": 0.1,
      "cy": 0.7,
      "radius": "0px",
      "accessibleName": null,
      "tag": "div"
     },
     "waveform": null,
     "artwork": {
      "w": 60,
      "h": 60,
      "areaShare": 0,
      "cx": 0.1,
      "cy": 0.2,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:00"
     ],
     "controlCount": 1,
     "outboundLinks": 1,
     "platformPush": false,
     "textLen": 121,
     "textSample": "Dateline NBC Verdict watch in a mother's murder trial. A firefighter's killer wife. Plus, extraditions 101. 00:00 / --:-",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 210
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(33, 37, 41)",
     "radius": "0px",
     "play": {
      "w": 60,
      "h": 60,
      "area": 3600,
      "via": "class",
      "cx": 0.1,
      "cy": 0.7,
      "radius": "0px",
      "accessibleName": null,
      "tag": "div"
     },
     "waveform": null,
     "artwork": {
      "w": 60,
      "h": 60,
      "areaShare": 0,
      "cx": 0.1,
      "cy": 0.2,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "00:00"
     ],
     "controlCount": 1,
     "outboundLinks": 1,
     "platformPush": false,
     "textLen": 121,
     "textSample": "Dateline NBC Verdict watch in a mother's murder trial. A firefighter's killer wife. Plus, extraditions 101. 00:00 / --:-",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 27,
    "kb": 558.9
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 210,
    "clientH": 210
   },
   "pixels": {
    "light": 242.9,
    "dark": 242.9
   },
   "themeResponds": false,
   "lightLuma": 242.9,
   "darkLuma": 242.9,
   "measured": true
  },
  "applemusic": {
   "id": "applemusic",
   "name": "Apple Music",
   "group": "other",
   "status": "caveat",
   "blocked": false,
   "declaredHeight": 450,
   "aspect": false,
   "themedParam": false,
   "shownMode": "live",
   "fellBack": true,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 450
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 30.9,
      "h": 20,
      "area": 617,
      "via": "class",
      "cx": 0.2,
      "cy": 0.9,
      "radius": "0px",
      "accessibleName": "Play",
      "tag": "span"
     },
     "waveform": null,
     "artwork": null,
     "progress": null,
     "timecodes": [],
     "controlCount": 15,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 0,
     "textSample": "",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 450
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 30.9,
      "h": 20,
      "area": 617,
      "via": "class",
      "cx": 0.2,
      "cy": 0.9,
      "radius": "0px",
      "accessibleName": "Play",
      "tag": "span"
     },
     "waveform": null,
     "artwork": null,
     "progress": null,
     "timecodes": [],
     "controlCount": 15,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 0,
     "textSample": "",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 36,
    "kb": 7.4
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 450,
    "clientH": 450
   },
   "pixels": {
    "light": 232.3,
    "dark": 232.3
   },
   "themeResponds": false,
   "lightLuma": 232.3,
   "darkLuma": 232.3,
   "measured": true
  },
  "tidal": {
   "id": "tidal",
   "name": "Tidal",
   "group": "other",
   "status": "caveat",
   "blocked": false,
   "declaredHeight": 120,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 120
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 88,
      "h": 88,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "1px",
      "isImg": true
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 398,
      "h": 4,
      "interactive": false
     },
     "timecodes": [],
     "controlCount": 4,
     "outboundLinks": 3,
     "platformPush": false,
     "textLen": 32,
     "textSample": "Along for the Ride Dream Theater",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 120
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(255, 255, 255)",
     "radius": "0px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 88,
      "h": 88,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "1px",
      "isImg": true
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 398,
      "h": 4,
      "interactive": false
     },
     "timecodes": [],
     "controlCount": 4,
     "outboundLinks": 3,
     "platformPush": false,
     "textLen": 32,
     "textSample": "Along for the Ride Dream Theater",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 26,
    "kb": 0.4
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 120,
    "clientH": 120
   },
   "pixels": {
    "light": 225.1,
    "dark": 10.3
   },
   "themeResponds": true,
   "lightLuma": 225.1,
   "darkLuma": 10.3,
   "measured": true
  },
  "npr": {
   "id": "npr",
   "name": "NPR",
   "group": "other",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 215,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 215
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 40,
      "h": 40,
      "area": 1600,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.7,
      "radius": "30px",
      "accessibleName": "Play audio",
      "tag": "a"
     },
     "waveform": null,
     "artwork": {
      "w": 139.7,
      "h": 139.7,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.4,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 383.3,
      "h": 10,
      "interactive": false
     },
     "timecodes": [
      "25:47"
     ],
     "controlCount": 6,
     "outboundLinks": 4,
     "platformPush": false,
     "textLen": 98,
     "textSample": "Sam Yellowhorse Kesler/NPR Share Planet Money Love in the time of Palantir Listen 25:47 \u00a9 2026 NPR",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 215
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 40,
      "h": 40,
      "area": 1600,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.7,
      "radius": "30px",
      "accessibleName": "Play audio",
      "tag": "a"
     },
     "waveform": null,
     "artwork": {
      "w": 139.7,
      "h": 139.7,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.4,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 383.3,
      "h": 10,
      "interactive": false
     },
     "timecodes": [
      "25:47"
     ],
     "controlCount": 6,
     "outboundLinks": 4,
     "platformPush": false,
     "textLen": 98,
     "textSample": "Sam Yellowhorse Kesler/NPR Share Planet Money Love in the time of Palantir Listen 25:47 \u00a9 2026 NPR",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 38,
    "kb": 371.3
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 215,
    "clientH": 215
   },
   "pixels": {
    "light": 208.2,
    "dark": 207.2
   },
   "themeResponds": false,
   "lightLuma": 208.2,
   "darkLuma": 207.2,
   "measured": true
  },
  "mixcloud": {
   "id": "mixcloud",
   "name": "Mixcloud",
   "group": "other",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 120,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 120
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(51, 51, 51)",
     "radius": "0px",
     "play": {
      "w": 30,
      "h": 30,
      "area": 900,
      "via": "class",
      "cx": 0.2,
      "cy": 0.3,
      "radius": "0px",
      "accessibleName": null,
      "tag": "div"
     },
     "waveform": null,
     "artwork": {
      "w": 120,
      "h": 120,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 308,
      "h": 10,
      "interactive": false
     },
     "timecodes": [
      "00:00",
      "59:51"
     ],
     "controlCount": 4,
     "outboundLinks": 4,
     "platformPush": false,
     "textLen": 76,
     "textSample": "Bridget Small - 2nd September 2026 by Mixcloud NTS Radio FOLLOW 00:00 -59:51",
     "settleSeconds": 4.4
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 120
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(51, 51, 51)",
     "radius": "0px",
     "play": {
      "w": 30,
      "h": 30,
      "area": 900,
      "via": "class",
      "cx": 0.2,
      "cy": 0.3,
      "radius": "0px",
      "accessibleName": null,
      "tag": "div"
     },
     "waveform": null,
     "artwork": {
      "w": 120,
      "h": 120,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 308,
      "h": 10,
      "interactive": false
     },
     "timecodes": [
      "00:00",
      "59:51"
     ],
     "controlCount": 4,
     "outboundLinks": 4,
     "platformPush": false,
     "textLen": 76,
     "textSample": "Bridget Small - 2nd September 2026 by Mixcloud NTS Radio FOLLOW 00:00 -59:51",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 59,
    "kb": 1288.5
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 120,
    "clientH": 120
   },
   "pixels": {
    "light": 66.1,
    "dark": 66.1
   },
   "themeResponds": false,
   "lightLuma": 66.1,
   "darkLuma": 66.1,
   "measured": true
  },
  "audiomack": {
   "id": "audiomack",
   "name": "Audiomack",
   "group": "other",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 266,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 266
     },
     "bg": "rgb(13, 13, 13)",
     "color": "rgb(255, 255, 255)",
     "radius": "0px",
     "play": {
      "w": 40,
      "h": 40,
      "area": 1600,
      "via": "aria-label",
      "cx": 0.1,
      "cy": 0.8,
      "radius": "50%",
      "accessibleName": "Play, Purple Reign",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 570,
      "h": 41
     },
     "artwork": {
      "w": 124,
      "h": 124,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.4,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "0:00",
      "4:02"
     ],
     "controlCount": 6,
     "outboundLinks": 4,
     "platformPush": false,
     "textLen": 136,
     "textSample": "Future Purple Reign This song is only available for premium subscribers. Start your free trial. Play Purple Reign 0:00 0",
     "settleSeconds": 5.6
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 266
     },
     "bg": "rgb(13, 13, 13)",
     "color": "rgb(255, 255, 255)",
     "radius": "0px",
     "play": {
      "w": 40,
      "h": 40,
      "area": 1600,
      "via": "aria-label",
      "cx": 0.1,
      "cy": 0.8,
      "radius": "50%",
      "accessibleName": "Play, Purple Reign",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 570,
      "h": 41
     },
     "artwork": {
      "w": 124,
      "h": 124,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.4,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "0:00",
      "4:02"
     ],
     "controlCount": 6,
     "outboundLinks": 4,
     "platformPush": false,
     "textLen": 136,
     "textSample": "Future Purple Reign This song is only available for premium subscribers. Start your free trial. Play Purple Reign 0:00 0",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 54,
    "kb": 62.4
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 266,
    "clientH": 266
   },
   "pixels": {
    "light": 14.1,
    "dark": 14.1
   },
   "themeResponds": false,
   "lightLuma": 14.1,
   "darkLuma": 14.1,
   "measured": true
  },
  "bandcamp": {
   "id": "bandcamp",
   "name": "Bandcamp",
   "group": "other",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 120,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 120
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 46,
      "h": 46,
      "area": 2116,
      "via": "class",
      "cx": 0.2,
      "cy": 0.7,
      "radius": "2px",
      "accessibleName": null,
      "tag": "div"
     },
     "waveform": null,
     "artwork": {
      "w": 120,
      "h": 120,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": false
     },
     "progress": null,
     "timecodes": [
      "00:00",
      "03:59"
     ],
     "controlCount": 5,
     "outboundLinks": 5,
     "platformPush": false,
     "textLen": 74,
     "textSample": "Carrie & Lowell buy share Sufjan Stevens 1. Death with Dignity 00:00 03:59",
     "settleSeconds": 6.1
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 120
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 46,
      "h": 46,
      "area": 2116,
      "via": "class",
      "cx": 0.2,
      "cy": 0.7,
      "radius": "2px",
      "accessibleName": null,
      "tag": "div"
     },
     "waveform": null,
     "artwork": {
      "w": 120,
      "h": 120,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": false
     },
     "progress": null,
     "timecodes": [
      "00:00",
      "03:59"
     ],
     "controlCount": 5,
     "outboundLinks": 5,
     "platformPush": false,
     "textLen": 74,
     "textSample": "Carrie & Lowell buy share Sufjan Stevens 1. Death with Dignity 00:00 03:59",
     "settleSeconds": 6.1
    }
   },
   "network": {
    "requests": 19,
    "kb": 572.5
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 120,
    "clientH": 120
   },
   "pixels": {
    "light": 220.3,
    "dark": 220.3
   },
   "themeResponds": false,
   "lightLuma": 220.3,
   "darkLuma": 220.3,
   "measured": true
  },
  "vimeo": {
   "id": "vimeo",
   "name": "Vimeo",
   "group": "other",
   "status": "ok",
   "blocked": false,
   "declaredHeight": null,
   "aspect": true,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 640,
      "h": 360,
      "areaShare": 1,
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "slider",
      "w": 348,
      "h": 4,
      "interactive": true
     },
     "timecodes": [
      "00:00",
      "01:02"
     ],
     "controlCount": 11,
     "outboundLinks": 1,
     "platformPush": false,
     "textLen": 140,
     "textSample": "Playing in picture-in-picture Sample Video Like Add to Watch Later Share Embed Play 00:00 01:02 Settings Speed Picture-i",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 640,
      "h": 360,
      "areaShare": 1,
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "slider",
      "w": 348,
      "h": 4,
      "interactive": true
     },
     "timecodes": [
      "00:00",
      "01:02"
     ],
     "controlCount": 11,
     "outboundLinks": 1,
     "platformPush": false,
     "textLen": 140,
     "textSample": "Playing in picture-in-picture Sample Video Like Add to Watch Later Share Embed Play 00:00 01:02 Settings Speed Picture-i",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 14,
    "kb": 0.9
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 360,
    "clientH": 360
   },
   "pixels": {
    "light": 166.4,
    "dark": 166.4
   },
   "themeResponds": false,
   "lightLuma": 166.4,
   "darkLuma": 166.4,
   "measured": true
  },
  "dailymotion": {
   "id": "dailymotion",
   "name": "Dailymotion",
   "group": "other",
   "status": "ok",
   "blocked": false,
   "declaredHeight": null,
   "aspect": true,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgb(13, 13, 13)",
     "color": "rgb(255, 255, 255)",
     "radius": "0px",
     "play": {
      "w": 80,
      "h": 80,
      "area": 6400,
      "via": "aria-label",
      "cx": 0.5,
      "cy": 0.5,
      "radius": "100px",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": null,
     "artwork": null,
     "progress": {
      "kind": "input",
      "w": 368,
      "h": 4,
      "interactive": true
     },
     "timecodes": [
      "0:04",
      "1:08:25"
     ],
     "controlCount": 10,
     "outboundLinks": 2,
     "platformPush": false,
     "textLen": 163,
     "textSample": "Top Gear Guy Finds His Mrs. Right #englishsubtitle #fullfilm #verticaldrama\ud83d\udca5\ud83c\udfac\u26a1\ufe0f | Drama Royals 0:04 1:08:25 Speed 2x C",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgb(13, 13, 13)",
     "color": "rgb(255, 255, 255)",
     "radius": "0px",
     "play": {
      "w": 80,
      "h": 80,
      "area": 6400,
      "via": "aria-label",
      "cx": 0.5,
      "cy": 0.5,
      "radius": "100px",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": null,
     "artwork": null,
     "progress": {
      "kind": "input",
      "w": 368,
      "h": 4,
      "interactive": true
     },
     "timecodes": [
      "0:04",
      "1:08:25"
     ],
     "controlCount": 10,
     "outboundLinks": 2,
     "platformPush": false,
     "textLen": 163,
     "textSample": "Top Gear Guy Finds His Mrs. Right #englishsubtitle #fullfilm #verticaldrama\ud83d\udca5\ud83c\udfac\u26a1\ufe0f | Drama Royals 0:04 1:08:25 Speed 2x C",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 101,
    "kb": 135.8
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 360,
    "clientH": 360
   },
   "pixels": {
    "light": 36.3,
    "dark": 36.1
   },
   "themeResponds": false,
   "lightLuma": 36.3,
   "darkLuma": 36.1,
   "measured": true
  },
  "tiktok": {
   "id": "tiktok",
   "name": "TikTok",
   "group": "other",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 740,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 740
     },
     "bg": "rgb(255, 255, 255)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 48,
      "h": 48,
      "areaShare": 0,
      "cx": 0.7,
      "cy": 0,
      "radius": "0px",
      "isImg": false
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 640,
      "h": 4,
      "interactive": false
     },
     "timecodes": [],
     "controlCount": 16,
     "outboundLinks": 15,
     "platformPush": false,
     "textLen": 252,
     "textSample": "35.2K 5849 1473 Watch more exciting videos on TikTok Watch more exciting videos on TikTokWatch more exciting videos on T",
     "settleSeconds": 4.4
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 740
     },
     "bg": "rgb(255, 255, 255)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 48,
      "h": 48,
      "areaShare": 0,
      "cx": 0.7,
      "cy": 0,
      "radius": "0px",
      "isImg": false
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 640,
      "h": 4,
      "interactive": false
     },
     "timecodes": [],
     "controlCount": 16,
     "outboundLinks": 15,
     "platformPush": false,
     "textLen": 252,
     "textSample": "35.2K 5849 1473 Watch more exciting videos on TikTok Watch more exciting videos on TikTokWatch more exciting videos on T",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 54,
    "kb": 360.0
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 740,
    "clientH": 740
   },
   "pixels": {
    "light": 210.4,
    "dark": 210.3
   },
   "themeResponds": false,
   "lightLuma": 210.4,
   "darkLuma": 210.3,
   "measured": true
  },
  "soundcloud": {
   "id": "soundcloud",
   "name": "SoundCloud",
   "group": "other",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 166,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 166
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(51, 51, 51)",
     "radius": "0px",
     "play": {
      "w": 43,
      "h": 43,
      "area": 1849,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.2,
      "radius": "0px",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 453,
      "h": 65
     },
     "artwork": {
      "w": 144,
      "h": 144,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": false
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 453,
      "h": 10,
      "interactive": false
     },
     "timecodes": [],
     "controlCount": 9,
     "outboundLinks": 5,
     "platformPush": false,
     "textLen": 116,
     "textSample": "Follow The Chainsmokers Closer (feat. Halsey) Share PREVIEW 5.9M plays 5.9M SoundCloud privacy policy Privacy policy",
     "settleSeconds": 4.4
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 166
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(51, 51, 51)",
     "radius": "0px",
     "play": {
      "w": 43,
      "h": 43,
      "area": 1849,
      "via": "aria-label",
      "cx": 0.3,
      "cy": 0.2,
      "radius": "0px",
      "accessibleName": "Play",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 453,
      "h": 65
     },
     "artwork": {
      "w": 144,
      "h": 144,
      "areaShare": 0.2,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": false
     },
     "progress": {
      "kind": "unlabelled bar",
      "w": 453,
      "h": 10,
      "interactive": false
     },
     "timecodes": [],
     "controlCount": 9,
     "outboundLinks": 5,
     "platformPush": false,
     "textLen": 116,
     "textSample": "Follow The Chainsmokers Closer (feat. Halsey) Share PREVIEW 5.9M plays 5.9M SoundCloud privacy policy Privacy policy",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 87,
    "kb": 8.2
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 166,
    "clientH": 166
   },
   "pixels": {
    "light": 221.0,
    "dark": 221.0
   },
   "themeResponds": false,
   "lightLuma": 221.0,
   "darkLuma": 221.0,
   "measured": true
  },
  "zeno": {
   "id": "zeno",
   "name": "Zeno.fm",
   "group": "other",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 250,
   "aspect": false,
   "themedParam": false,
   "shownMode": "live",
   "fellBack": true,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 266
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 105,
      "h": 60,
      "area": 6300,
      "via": "class",
      "cx": 0.1,
      "cy": 0.8,
      "radius": "0px",
      "accessibleName": null,
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 133.4,
      "h": 75,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 6,
     "outboundLinks": 3,
     "platformPush": false,
     "textLen": 105,
     "textSample": "Get It On Google Play Available on the App Store ESPN Radio - KVSF Share on Social Media Facebook Twitter",
     "settleSeconds": 4.4
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 266
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 105,
      "h": 60,
      "area": 6300,
      "via": "class",
      "cx": 0.1,
      "cy": 0.8,
      "radius": "0px",
      "accessibleName": null,
      "tag": "button"
     },
     "waveform": null,
     "artwork": {
      "w": 133.4,
      "h": 75,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 6,
     "outboundLinks": 3,
     "platformPush": false,
     "textLen": 105,
     "textSample": "Get It On Google Play Available on the App Store ESPN Radio - KVSF Share on Social Media Facebook Twitter",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 146,
    "kb": 55.4
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 266,
    "clientH": 250
   },
   "pixels": {
    "light": 111.8,
    "dark": 111.8
   },
   "themeResponds": false,
   "lightLuma": 111.8,
   "darkLuma": 111.8,
   "measured": true
  },
  "wistia": {
   "id": "wistia",
   "name": "Wistia",
   "group": "infra",
   "status": "ok",
   "blocked": false,
   "declaredHeight": null,
   "aspect": true,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 40,
      "h": 34,
      "area": 1360,
      "via": "aria-label",
      "cx": 0,
      "cy": 1,
      "radius": "0px",
      "accessibleName": "Play Video",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 441,
      "h": 34
     },
     "artwork": {
      "w": 640,
      "h": 360,
      "areaShare": 1,
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "slider",
      "w": 418.6,
      "h": 34,
      "interactive": true
     },
     "timecodes": [
      "0:44"
     ],
     "controlCount": 6,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 29,
     "textSample": "Press O for more options 0:44",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 40,
      "h": 34,
      "area": 1360,
      "via": "aria-label",
      "cx": 0,
      "cy": 1,
      "radius": "0px",
      "accessibleName": "Play Video",
      "tag": "button"
     },
     "waveform": {
      "kind": "canvas",
      "count": null,
      "w": 441,
      "h": 34
     },
     "artwork": {
      "w": 640,
      "h": 360,
      "areaShare": 1,
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": {
      "kind": "slider",
      "w": 418.6,
      "h": 34,
      "interactive": true
     },
     "timecodes": [
      "0:44"
     ],
     "controlCount": 6,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 29,
     "textSample": "Press O for more options 0:44",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 18,
    "kb": null
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 360,
    "clientH": 360
   },
   "pixels": {
    "light": 129.7,
    "dark": 129.7
   },
   "themeResponds": false,
   "lightLuma": 129.7,
   "darkLuma": 129.7,
   "measured": true
  },
  "streamable": {
   "id": "streamable",
   "name": "Streamable",
   "group": "infra",
   "status": "ok",
   "blocked": false,
   "declaredHeight": null,
   "aspect": true,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 639,
      "h": 360,
      "areaShare": 1,
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 0,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 0,
     "textSample": "",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 639,
      "h": 360,
      "areaShare": 1,
      "cx": 0.5,
      "cy": 0.5,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 0,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 0,
     "textSample": "",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 7,
    "kb": 225.4
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 360,
    "clientH": 360
   },
   "pixels": {
    "light": 145.6,
    "dark": 145.6
   },
   "themeResponds": false,
   "lightLuma": 145.6,
   "darkLuma": 145.6,
   "measured": true
  },
  "odysee": {
   "id": "odysee",
   "name": "Odysee",
   "group": "infra",
   "status": "ok",
   "blocked": false,
   "declaredHeight": null,
   "aspect": true,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 160,
      "h": 160,
      "areaShare": 0.1,
      "cx": 0.5,
      "cy": 0.3,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 2,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 51,
     "textSample": "No Content Found Publish Something Repost Something",
     "settleSeconds": 4.4
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 360
     },
     "bg": "rgba(0, 0, 0, 0)",
     "color": "rgb(255, 255, 255)",
     "radius": "0px",
     "play": null,
     "waveform": null,
     "artwork": {
      "w": 160,
      "h": 160,
      "areaShare": 0.1,
      "cx": 0.5,
      "cy": 0.3,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [],
     "controlCount": 2,
     "outboundLinks": 0,
     "platformPush": false,
     "textLen": 51,
     "textSample": "No Content Found Publish Something Repost Something",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 112,
    "kb": 1404.7
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 360,
    "clientH": 360
   },
   "pixels": {
    "light": 32.7,
    "dark": 29.7
   },
   "themeResponds": false,
   "lightLuma": 32.7,
   "darkLuma": 29.7,
   "measured": true
  },
  "ivoox": {
   "id": "ivoox",
   "name": "iVoox",
   "group": "hosts",
   "status": "ok",
   "blocked": false,
   "declaredHeight": 200,
   "aspect": false,
   "themedParam": false,
   "shownMode": "podcast",
   "fellBack": false,
   "schemes": {
    "light": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgb(249, 249, 249)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 136,
      "h": 47,
      "area": 6392,
      "via": "class",
      "cx": 0.1,
      "cy": 0.8,
      "radius": "0px",
      "accessibleName": "PLAY",
      "tag": "a"
     },
     "waveform": null,
     "artwork": {
      "w": 135,
      "h": 135,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.3,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "0:00:00",
      "02:07:57"
     ],
     "controlCount": 7,
     "outboundLinks": 5,
     "platformPush": true,
     "textLen": 105,
     "textSample": "By cope 03 SEP 2026 | EL PARTIDAZO DE COPE 21 Download Subscribe Share Download APP 0:00:00 02:07:57 PLAY",
     "settleSeconds": 4.3
    },
    "dark": {
     "frame": {
      "w": 640,
      "h": 200
     },
     "bg": "rgb(249, 249, 249)",
     "color": "rgb(0, 0, 0)",
     "radius": "0px",
     "play": {
      "w": 136,
      "h": 47,
      "area": 6392,
      "via": "class",
      "cx": 0.1,
      "cy": 0.8,
      "radius": "0px",
      "accessibleName": "PLAY",
      "tag": "a"
     },
     "waveform": null,
     "artwork": {
      "w": 135,
      "h": 135,
      "areaShare": 0.1,
      "cx": 0.1,
      "cy": 0.3,
      "radius": "0px",
      "isImg": true
     },
     "progress": null,
     "timecodes": [
      "0:00:00",
      "02:07:57"
     ],
     "controlCount": 7,
     "outboundLinks": 5,
     "platformPush": true,
     "textLen": 105,
     "textSample": "By cope 03 SEP 2026 | EL PARTIDAZO DE COPE 21 Download Subscribe Share Download APP 0:00:00 02:07:57 PLAY",
     "settleSeconds": 4.3
    }
   },
   "network": {
    "requests": 13,
    "kb": 45.2
   },
   "narrow": {
    "scrollW": 375,
    "clientW": 375,
    "scrollH": 210,
    "clientH": 200
   },
   "pixels": {
    "light": 206.5,
    "dark": 206.5
   },
   "themeResponds": false,
   "lightLuma": 206.5,
   "darkLuma": 206.5,
   "measured": true
  },
  "amazonmusic": {
   "id": "amazonmusic",
   "name": "Amazon Music",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "Sends X-Frame-Options SAMEORIGIN",
   "measured": false
  },
  "youtubemusic": {
   "id": "youtubemusic",
   "name": "YouTube Music",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "Sends X-Frame-Options SAMEORIGIN",
   "measured": false
  },
  "pocketcasts": {
   "id": "pocketcasts",
   "name": "Pocket Casts",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "Sends X-Frame-Options SAMEORIGIN",
   "measured": false
  },
  "radionet": {
   "id": "radionet",
   "name": "Radio.net",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "CSP frame-ancestors allows only its own CMS domains",
   "measured": false
  },
  "live365": {
   "id": "live365",
   "name": "Live365",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "Sends X-Frame-Options DENY",
   "measured": false
  },
  "pandora": {
   "id": "pandora",
   "name": "Pandora",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "No public embed exists",
   "measured": false
  },
  "siriusxm": {
   "id": "siriusxm",
   "name": "SiriusXM",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "Subscriber-login app, no embed product",
   "measured": false
  },
  "globalplayer": {
   "id": "globalplayer",
   "name": "Global Player",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "Sends X-Frame-Options SAMEORIGIN",
   "measured": false
  },
  "audacy": {
   "id": "audacy",
   "name": "Audacy",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "Sends X-Frame-Options SAMEORIGIN for third parties",
   "measured": false
  },
  "bbcsounds": {
   "id": "bbcsounds",
   "name": "BBC Sounds",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "No embed product, and UK geo-restricted",
   "measured": false
  },
  "substack": {
   "id": "substack",
   "name": "Substack",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "No outbound podcast embed exists",
   "measured": false
  },
  "streema": {
   "id": "streema",
   "name": "Streema",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "No embed product",
   "measured": false
  },
  "radiogarden": {
   "id": "radiogarden",
   "name": "Radio Garden",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "No iframe player",
   "measured": false
  },
  "radiofrance": {
   "id": "radiofrance",
   "name": "Radio France",
   "group": "blocked",
   "status": "blocked",
   "blocked": true,
   "why": "Sends X-Frame-Options DENY",
   "measured": false
  }
 }
};
